apiVersion: v1
kind: Service
metadata:
  name: smart-app-service
  labels:
    app: smart-app
spec:
  selector:
      app: smart-app
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort : 80